export const LOADING_STATE = 'LOADING_STATE';
export const SALES_COLLECTION = 'SALES_COLLECTION';
export const TOPSELLERS_COLLECTION = 'TOPSELLERS_COLLECTION';
export const PARTS_COLLECTION = 'PARTS_COLLECTION';
export const PARTS_COLLECTION_CLEAR = 'PARTS_COLLECTION_CLEAR';